// 地图
const SET_MAP_LOAD_STATE = 'SET_MAP_LOAD_STATE'

//时间控件
const SET_PLAY_TIME = 'SET_PLAY_TIME'

//天气提示
const SET_WEATHER_TIP = 'SET_WEATHER_TIP'

//地图
export {
  SET_MAP_LOAD_STATE,
  SET_PLAY_TIME,
  SET_WEATHER_TIP
}
