// 地图
const SET_MAP_LOAD_STATE = 'SET_MAP_LOAD_STATE'

//时间控件
const SET_PLAY_TIME = 'SET_PLAY_TIME'

//天气提示
const SET_WEATHER_TIP = 'SET_WEATHER_TIP'
const SHOW_WEATHER_TIP = 'SHOW_WEATHER_TIP'

//图例
const SET_WEATHER_LEGEND = 'SET_WEATHER_LEGEND'
const SHOW_WEATHER_LEGEND = 'SHOW_WEATHER_LEGEND'

//天气要素切换
const SET_WEATHER_TYPE = 'SET_WEATHER_TYPE'

//地图
export {
  SET_MAP_LOAD_STATE,
  SET_PLAY_TIME,
  SET_WEATHER_TIP,
  SHOW_WEATHER_TIP,
  SET_WEATHER_LEGEND,
  SHOW_WEATHER_LEGEND,
  SET_WEATHER_TYPE
}
